---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:026090546401:task-definition/python:2"
        LoadBalancerInfo:
          ContainerName: "python"
          ContainerPort: 5000
